before_install:
  - gem install bundler 
language: ruby
script: 'bundle exec rake ci --trace'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  # - jruby-19mode Disabled for coredump http://travis-ci.org/#!/mbj/mapper/jobs/1778711
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
