require 'mapper/version'

require 'mapper/mapper'
require 'mapper/mapper/resource'
require 'mapper/mapper/attribute'
require 'mapper/mapper/embedded_collection'
require 'mapper/mapper/embedded_document'
require 'mapper/mapper/embedded_value'
require 'mapper/mapper/virtus'
require 'mapper/mapper/repository'
require 'mapper/mapper/root'
