---
AbcMetricMethodCheck:           
  score: 6.0
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 257 }
ClassNameCheck:                  
  pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 1 }
CyclomaticComplexityMethodCheck: { complexity: 2 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
MethodLineCountCheck:            { line_count: 8 }
MethodNameCheck:                 
  pattern: !ruby/regexp /\A(?:[a-z\d](?:_?[a-z\d])+[?!=]?|\[\]=?|==|<=>|<<|[+*&|-])\z/
ModuleLineCountCheck:            { line_count: 260 }
ModuleNameCheck:                 
  pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/
ParameterNumberCheck:            { parameter_count: 2 }
